name: Example Workflow
on:
  workflow_dispatch:
jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use secret in script
        env:
          MY_SECRET_1: ${{ secrets.NOTIFICATION_TELEGRAM }}
          MY_SECRET_2: ${{ secrets.NOTIFICATION_TELEGRAM_BOT_KEY }}
          MY_SECRET_3: ${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }}
        run: |
          echo "My secret value: $MY_SECRET"
          # Use $MY_SECRET in your script
